name: run renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "23 * * * *"

permissions: {}

concurrency:
  group: renovate
  cancel-in-progress: false

jobs:
  renovate:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      contents: read
      packages: read
    steps:
      - name: Run dependency updates
        uses: a-novel-kit/workflows/generic-actions/renovate@v1.29.1
        with:
          github_token: ${{ github.token }}
          app_private_key: ${{ secrets.DEPENDENCY_BOT_PRIVATE_KEY }}
          client_id: ${{ vars.DEPENDENCY_BOT_CLIENT_ID }}
